---
- hosts: ciao_controller:ciao_compute:ciao_network
  tasks:

    # In ansible 2.2.0 we can drop ignore errors since it will not fail
    # when the services does not exist.
    - name: Stop services
      service: name={{ item }} enabled=no state=stopped
      with_items:
        - ciao-network.service
        - ciao-compute.service
        - ciao-controller.service
        - ciao-scheduler.service
      ignore_errors: yes

    - name: Remove CIAO Service files
      file: name={{ item }} state=absent
      with_items:
        - /etc/systemd/system/ciao-network.service
        - /etc/systemd/system/ciao-compute.service
        - /etc/systemd/system/ciao-scheduler.service
        - /etc/systemd/system/ciao-controller.service

    - name: Remove CIAO directories
      file: path={{ item }} state=absent
      with_items:
        - /etc/ca-certs
        - /etc/ciao
        - /etc/pki/ciao
        - /etc/ssl/certs
        - /var/lib/ciao

    - name: Remove CIAO files from github
      file: path={{ item }} state=absent
      with_items:
        - ~/go
        - /usr/local/bin/ciao-controller
        - /usr/local/bin/ciao-scheduler
        - /usr/local/bin/ciao-launcher
        - /usr/local/bin/ciao-cli
        - /usr/local/bin/ciao-cert
        - /usr/local/bin/ciao-cnci-agent
      when: ciao_dev
