---
# Copyright (c) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

  - name: Create /usr/share/qemu directory
    file: path=/usr/share/qemu state=directory

  - name: Download OVMF.fd
    copy: src=images/OVMF.fd dest=/usr/share/qemu/OVMF.fd
    when: ansible_os_family == "Debian"

  - name: Download Fedora Image
    copy: src=images/{{ fedora_cloud_image }} dest=/var/lib/ciao/images/{{ fedora_cloud_image }}

  - name: Link fedora image to its reference in the DB
    file:
      path: /var/lib/ciao/images/73a86d7e-93c0-480e-9c41-ab42f69b7799
      src: /var/lib/ciao/images/{{ fedora_cloud_image }}
      state: link

  - name: Download ClearLinux Image
    copy: src=images/{{ clear_cloud_image }} dest=/var/lib/ciao/images/{{ clear_cloud_image }}

  - name: Link clear linux image to its reference in the DB
    file:
      path: /var/lib/ciao/images/df3768da-31f5-4ba6-82f0-127a1a705169
      src: /var/lib/ciao/images/{{ clear_cloud_image }}
      state: link
