---
- name: get ceph version
  command: ceph --version
  changed_when: false
  always_run: true
  register: ceph_version

- set_fact:
    ceph_version: "{{ ceph_version.stdout.split(' ')[2] }}"

# NOTE(mattt): On ansible 2.x we can use ansible_service_mgr instead
- name: check init system
  slurp:
    src: /proc/1/comm
  always_run: true
  register: init_system

- set_fact:
    init_system={{ init_system.content | b64decode | trim }}

- set_fact:
    use_systemd={{ init_system.strip() == 'systemd' }}

- set_fact:
    mds_name: "{{ ansible_hostname }}"
  when: not mds_use_fqdn

- set_fact:
    mds_name: "{{ ansible_fqdn }}"
  when: mds_use_fqdn
