---
- name: get ceph version
  command: ceph --version
  changed_when: false
  always_run: yes
  register: ceph_version

# this task shouldn't run in a rolling_update situation
# because it blindly picks a mon, which may be down because
# of the rolling update
- name: is ceph running already?
  command: ceph --connect-timeout 3 --cluster {{ cluster }} fsid
  changed_when: false
  failed_when: false
  always_run: yes
  register: ceph_current_fsid
  delegate_to: "{{ groups[mon_group_name][0] }}"
  when: not rolling_update

# set this as a default when performing a rolling_update
# so the rest of the tasks here will succeed
- set_fact:
    ceph_current_fsid:
      rc: 1
  when: rolling_update

- name: create a local fetch directory if it does not exist
  local_action: file path={{ fetch_directory }} state=directory
  changed_when: false
  become: false
  run_once: true
  when: cephx or generate_fsid

- set_fact:
    fsid: "{{ ceph_current_fsid.stdout }}"
  when:
    - ceph_current_fsid.rc == 0

- set_fact:
    monitor_name: "{{ ansible_hostname }}"
  when: not mon_use_fqdn

- set_fact:
    monitor_name: "{{ ansible_fqdn }}"
  when: mon_use_fqdn

# We want this check to be run only on one mon
- name: check if {{ fetch_directory }} directory exists
  local_action: stat path="{{ fetch_directory }}/monitor_keyring.conf"
  become: false
  register: monitor_keyring_conf
  run_once: true

- include: facts_mon_fsid.yml
  run_once: true
  when:
    - cephx
    - not monitor_keyring_conf.stat.exists
    - ceph_current_fsid.rc == 0
    - mon_group_name in group_names

- set_fact:
    ceph_version: "{{ ceph_version.stdout.split(' ')[2] }}"

- set_fact:
    mds_name: "{{ ansible_hostname }}"
  when: not mds_use_fqdn

- set_fact:
    mds_name: "{{ ansible_fqdn }}"
  when: mds_use_fqdn

- set_fact:
    rbd_client_directory_owner: ceph
  when:
    - rbd_client_directory_owner is not defined
      or not rbd_client_directory_owner

- set_fact:
    rbd_client_directory_group: ceph
  when:
    - rbd_client_directory_group is not defined
      or not rbd_client_directory_group

- set_fact:
    rbd_client_directory_mode: "0770"
  when:
    - rbd_client_directory_mode is not defined
      or not rbd_client_directory_mode

