---
- name: create ceph conf directory
  file:
    path: /etc/ceph
    state: directory
    owner: "ceph"
    group: "ceph"
    mode: "0755"

- name: "generate ceph configuration file: {{ cluster }}.conf"
  action: config_template
  args:
    src: ceph.conf.j2
    dest: /etc/ceph/{{ cluster }}.conf
    owner: "ceph"
    group: "ceph"
    mode: "0644"
    config_overrides: "{{ ceph_conf_overrides }}"
    config_type: ini
  notify:
    - restart ceph mons
    - restart ceph osds
    - restart ceph mdss
    - restart ceph rgws
    - restart ceph nfss
