---
- name: create ceph conf directory
  file:
    path: /etc/ceph
    state: directory
    owner: "{{ dir_owner }}"
    group: "{{ dir_group }}"
    mode: "{{ dir_mode }}"

- name: "generate ceph configuration file: {{ cluster }}.conf"
  action: config_template
  args:
    src: ceph.conf.j2
    dest: /etc/ceph/{{ cluster }}.conf
    owner: "{{ dir_owner }}"
    group: "{{ dir_group }}"
    mode: "{{ activate_file_mode }}"
    config_overrides: "{{ ceph_conf_overrides }}"
    config_type: ini
  notify:
    - restart ceph mons
    - restart ceph mons on ubuntu
    - restart ceph mons with systemd
    - restart ceph osds
    - restart ceph osds on ubuntu
    - restart ceph osds with systemd
    - restart ceph mdss
    - restart ceph mdss on ubuntu
    - restart ceph mdss with systemd
    - restart ceph rgws
    - restart ceph rgws on ubuntu
    - restart ceph rgws on red hat
    - restart ceph rgws with systemd
    - restart ceph nfss
