---
- name: update apt cache
  apt:
    update-cache: yes
  when: ansible_os_family == 'Debian'

- name: restart ceph mons
  include: "./restart-mon.yml"

- name: restart ceph osds
  include: "./restart-osd.yml"

- name: restart ceph mdss
  include: "./restart-mds.yml"

- name: restart ceph rgws
  include: "./restart-rgw.yml"

- name: restart ceph nfss
  service:
    name: nfs-ganesha
    state: restarted
  when:
    - nfs_group_name in group_names
