---
- name: install redhat dependencies via yum
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ redhat_package_dependencies }}"
  when:
    - ansible_distribution == "RedHat"
    - ansible_pkg_mgr == "yum"

- name: install redhat dependencies via dnf
  dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ redhat_package_dependencies }}"
  when:
    - ansible_distribution == "RedHat"
    - ansible_pkg_mgr == "dnf"

- name: install centos dependencies via yum
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ centos_package_dependencies }}"
  when:
    - ansible_distribution == "CentOS"
    - ansible_pkg_mgr == "yum"

- name: install centos dependencies via dnf
  dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ centos_package_dependencies }}"
  when:
    - ansible_distribution == "CentOS"
    - ansible_pkg_mgr == "dnf"

- name: configure ceph yum repository
  include: redhat_ceph_repository.yml
  when: ceph_origin == 'upstream'

- name: make sure /tmp exists
  file:
    path: /tmp
    state: directory
  when:
    - ceph_origin == 'local'
    - use_installer

- name: use mktemp to create name for rundep
  command: "mktemp /tmp/rundep.XXXXXXXX"
  register: rundep_location
  when:
    - ceph_origin == 'local'
    - use_installer

- name: copy rundep
  copy:
    src: "{{ansible_dir}}/rundep"
    dest: "{{ item }}"
  with_items: "{{ (rundep_location|default({})).stdout_lines|default([]) }}"
  when:
    - ceph_origin == 'local'
    - use_installer

- name: install ceph dependencies
  script: "{{ ansible_dir }}/rundep_installer.sh {{ item }}"
  become: true
  with_items: "{{ (rundep_location|default({})).stdout_lines|default([]) }}"
  when:
    - ceph_origin == 'local'
    - use_installer

- name: install ceph
  yum:
    name: ceph
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - ceph_release_num.{{ ceph_release }} <= ceph_release_num.infernalis
    - ansible_pkg_mgr == "yum"
    - ceph_origin != 'local'

- name: synchronize ceph install
  synchronize:
    src: "{{ceph_installation_dir}}/"
    dest: "/"
  when:
    - ceph_origin == 'local'

- name: create user group ceph
  group:
    name: 'ceph'
  when:
    - ceph_origin == 'local'

- name: create user ceph
  user:
    name: 'ceph'
  when:
    - ceph_origin == 'local'

- name: install distro or red hat storage ceph mon via yum
  yum:
    name: "ceph-mon"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - mon_group_name in group_names
    - ansible_pkg_mgr == "yum"
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.infernalis
      or ceph_origin == "distro"
      or ceph_custom

- name: install distro or red hat storage ceph mon via dnf
  dnf:
    name: "ceph-mon"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - mon_group_name in group_names
    - ansible_pkg_mgr == "dnf"
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.infernalis
      or ceph_origin == "distro"
      or ceph_custom

- name: install distro or red hat storage ceph osd via yum
  yum:
    name: "ceph-osd"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - osd_group_name in group_names
    - ansible_pkg_mgr == "yum"
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.infernalis
      or ceph_origin == "distro"
      or ceph_custom

- name: install distro or red hat storage ceph osd via dnf
  dnf:
    name: "ceph-osd"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - osd_group_name in group_names
    - ansible_pkg_mgr == "dnf"
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.infernalis
      or ceph_origin == "distro"
      or ceph_custom

- name: install distro or red hat storage ceph mds via yum
  yum:
    name: "ceph-mds"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - mds_group_name in group_names
    - ansible_pkg_mgr == "yum"
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.infernalis
      or ceph_origin == "distro"
      or ceph_custom

- name: install distro or red hat storage ceph mds via dnf
  dnf:
    name: "ceph-mds"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - mds_group_name in group_names
    - ansible_pkg_mgr == "dnf"
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.infernalis
      or ceph_origin == "distro"
      or ceph_custom

- name: install distro or red hat storage ceph-fuse via yum
  yum:
    name: "ceph-fuse"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - client_group_name in group_names
    - ansible_pkg_mgr == "yum"
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.infernalis
      or ceph_origin == "distro"
      or ceph_dev
      or ceph_custom

- name: install distro or red hat storage ceph-fuse via dnf
  dnf:
    name: "ceph-fuse"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - client_group_name in group_names
    - ansible_pkg_mgr == "dnf"
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.infernalis
      or ceph_origin == "distro"
      or ceph_dev
      or ceph_custom

- name: install distro or red hat storage ceph base via yum
  yum:
    name: "ceph-base"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - client_group_name in group_names
    - ansible_pkg_mgr == "yum"
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.infernalis
      or ceph_origin == "distro"
      or ceph_custom

- name: install distro or red hat storage ceph base via dnf
  dnf:
    name: "ceph-base"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - client_group_name in group_names
    - ansible_pkg_mgr == "dnf"
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.infernalis
      or ceph_origin == "distro"
      or ceph_custom

- name: install ceph-test
  yum:
    name: ceph-test
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - ceph_test
    - ansible_pkg_mgr == "yum"

- name: install ceph-test
  dnf:
    name: ceph-test
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - ceph_test
    - ansible_pkg_mgr == "dnf"

- name: install rados gateway
  yum:
    name: ceph-radosgw
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - rgw_group_name in group_names
    - ansible_pkg_mgr == "yum"

- name: install rados gateway
  dnf:
    name: ceph-radosgw
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - rgw_group_name in group_names
    - ansible_pkg_mgr == "dnf"

- name: install nfs ceph gateway
  yum:
    name: nfs-ganesha-ceph
  when:
    - nfs_group_name in group_names
    - ansible_pkg_mgr == "yum"
    - nfs_file_gw

- name: install nfs ceph gateway
  dnf:
    name: nfs-ganesha-ceph
  when:
    - nfs_group_name in group_names
    - ansible_pkg_mgr == "dnf"
    - nfs_file_gw

- name: install nfs rgw gateway
  yum:
    name: "{{ item }}"
  with_items:
    - nfs-ganesha-rgw
    - ceph-radosgw
  when:
    - nfs_group_name in group_names
    - ansible_pkg_mgr == "yum"
    - nfs_obj_gw

- name: install nfs rgw gateway
  dnf:
    name: "{{ item }}"
  with_items:
    - nfs-ganesha-rgw
    - ceph-radosgw
  when:
    - nfs_group_name in group_names
    - ansible_pkg_mgr == "dnf"
    - nfs_obj_gw
