---
- hosts: ciao_controller:ciao_compute:ciao_network
  tasks:

    # In ansible 2.2.0 we can drop ignore errors since it will not fail
    # when the services does not exist.
    - name: Stop services
      service: name={{ item }} enabled=no state=stopped
      with_items:
        - ciao-network.service
        - ciao-compute.service
        - ciao-controller.service
        - ciao-scheduler.service
      ignore_errors: yes

    - name: Remove CIAO Service files
      file: name={{ item }} state=absent
      with_items:
        - /etc/systemd/system/ciao-network.service
        - /etc/systemd/system/ciao-compute.service
        - /etc/systemd/system/ciao-scheduler.service
        - /etc/systemd/system/ciao-controller.service

    - name: Remove CIAO files
      file: path={{ item }} state=absent
      with_items:
        - /etc/ciao
        - /etc/pki/ciao
        - /etc/pki/keystone
        - /var/lib/ciao
        - /etc/ssl/certs/controller_cert.pem
        - /etc/ca-certificates/controller_cert.pem
        - /usr/local/share/ca-certificates/controller_cert.crt

    - name: Remove CIAO files from github
      file: path={{ item }} state=absent
      with_items:
        - ~/go
        - /usr/bin/ciao-controller
        - /usr/bin/ciao-scheduler
        - /usr/bin/ciao-launcher
        - /usr/bin/ciao-cli
        - /usr/bin/ciao-cert
        - /usr/bin/ciao-cnci-agent

    - name: Remove CIAO user
      user:
        name: ciao
        state: absent
        remove: yes
      when: ansible_distribution == 'Ubuntu'
