---
- hosts: localhost
  connection: local
  tasks:
    - name: Remove local files
      local_action: file path={{ item }} state=absent
      with_items:
        - ./openrc
        - ./ciaorc
        - ./clouds.yaml
        - ./certificates
        - ./images
        - ~/go
        - /var/lib/mysql/

- hosts: controllers
  tasks:
    - name: Stop ciao-webui docker container
      docker_container: name=ciao-webui state=absent

- hosts: controllers:computes:networks
  tasks:
    # In ansible 2.2.0 we can drop ignore errors since it will not fail
    # when the services does not exist.
    - name: Stop services
      service: name={{ item }} enabled=no state=stopped
      with_items:
        - ciao-network.service
        - ciao-compute.service
        - ciao-controller.service
        - ciao-scheduler.service
      ignore_errors: yes

    - name: Remove CIAO Service files
      file: name={{ item }} state=absent
      with_items:
        - /etc/systemd/system/ciao-network.service
        - /etc/systemd/system/ciao-compute.service
        - /etc/systemd/system/ciao-scheduler.service
        - /etc/systemd/system/ciao-controller.service

    - name: Remove CIAO files
      file: path={{ item }} state=absent
      with_items:
        - /etc/ciao
        - /etc/pki/ciao
        - /etc/pki/keystone
        - /var/lib/ciao
        - /etc/ssl/certs/keystone_cert.pem
        - /etc/ca-certificates/keystone_cert.pem
        - /usr/local/share/ca-certificates/keystone_cert.crt

    - name: Remove CIAO files from github
      file: path={{ item }} state=absent
      with_items:
        - /usr/bin/ciao-controller
        - /usr/bin/ciao-scheduler
        - /usr/bin/ciao-launcher
        - /usr/bin/ciao-cli
        - /usr/bin/ciao-cert
        - /usr/bin/ciao-cnci-agent

    - name: Remove CIAO user
      user:
        name: ciao
        state: absent
        remove: yes
      when: ansible_distribution == 'Ubuntu'
