---
- name: check if the device is a partition (autodiscover disks)
  shell: "readlink -f /dev/{{ item.key }} | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}$'"
  with_dict: "{{ ansible_devices }}"
  changed_when: false
  failed_when: false
  register: ispartition_results
  when:
    - ansible_devices is defined
    - item.value.removable == "0"

- name: check the partition status of the osd disks (autodiscover disks)
  shell: "parted --script /dev/{{ item.key }} print > /dev/null 2>&1"
  with_dict: "{{ ansible_devices }}"
  changed_when: false
  failed_when: false
  register: osd_partition_status_results
  when:
    - journal_collocation or raw_multi_journal
    - ansible_devices is defined
    - item.value.removable == "0"
    - item.value.partitions|count == 0

- name: fix partitions gpt header or labels of the osd disks (autodiscover disks)
  shell: "sgdisk --zap-all --clear --mbrtogpt -- '/dev/{{ item.0.item.key }}' || sgdisk --zap-all --clear --mbrtogpt -- '/dev/{{ item.0.item.key }}'"
  with_together:
    - "{{ osd_partition_status_results.results }}"
    - "{{ ansible_devices }}"
  changed_when: false
  when:
    - journal_collocation
    - ansible_devices is defined
    - item.0.item.value.removable == "0"
    - item.0.item.value.partitions|count == 0
    - item.0.rc != 0

- name: check if a partition named 'ceph' exists (autodiscover disks)
  shell: "parted --script /dev/{{ item.key }} print | egrep -sq '^ 1.*ceph'"
  with_dict: "{{ ansible_devices }}"
  changed_when: false
  failed_when: false
  register: parted_results
  when:
    - ansible_devices is defined
    - item.value.removable == "0"
