---
- include: deploy_monitors.yml
  when: not mon_containerized_deployment

- include: start_monitor.yml
  when: not mon_containerized_deployment

- include: ceph_keys.yml
  when: not mon_containerized_deployment
  # this avoids the bug mentioned here: https://github.com/ansible/ansible/issues/18206
  static: no

- include: create_mds_filesystems.yml
  when:
    - not mon_containerized_deployment
    - groups[mds_group_name] is defined
    - "{{ groups[mds_group_name]|length > 0 }}"
    - inventory_hostname == groups.mons|last

- include: secure_cluster.yml
  when:
    - secure_cluster
    - not mon_containerized_deployment

- include: ./docker/main.yml
  when: mon_containerized_deployment

- include: calamari.yml
  when: calamari
