---
- name: collect all the pools
  command: rados --cluster {{ cluster }} lspools
  register: ceph_pools
  always_run: true

- name: secure the cluster
  command: ceph --cluster {{ cluster }} osd pool set {{ item[0] }} {{ item[1] }} true
  with_nested:
    - "{{ ceph_pools.stdout_lines|default([]) }}"
    - "{{ secure_cluster_flags }}"
