---
- name: start the monitor service
  service:
    name: ceph-mon@{{ monitor_name }}
    state: started
    enabled: yes
  changed_when: false

- name: Enable ceph-mon.target
  service: name=ceph-mon.target enabled=yes
  when: ansible_os_family == 'Clear linux software for intel architecture'
