---
# Copyright (c) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

  - name: Create keystone service
    keystone:
      command: "ensure_service"
      service_name: "keystone"
      service_type: "identity"
      description: "OpenStack Identity"
      endpoint: "http://{{ groups['openstack_identity'][0] }}:{{keystone_admin_port}}/v3"
      login_user: admin
      login_password: "{{ keystone_admin_password }}"
      login_project_name: "admin"

  - name: Create keystone endpoints
    keystone:
      command: "ensure_endpoint"
      region_name: "RegionOne"
      service_name: "keystone"
      service_type: "identity"
      endpoint_list:
        - url: "http://{{ groups['openstack_identity'][0] }}:{{keystone_public_port}}/v3"
          interface: "public"
        - url: "http://{{ groups['openstack_identity'][0] }}:{{keystone_admin_port}}/v3"
          interface: "admin"
        - url: "http://{{ groups['openstack_identity'][0] }}:{{keystone_public_port}}/v3"
          interface: "internal"
      endpoint: "http://{{ groups['openstack_identity'][0] }}:{{keystone_admin_port}}/v3"
      login_user: admin
      login_password: "{{ keystone_admin_password }}"
      login_project_name: "admin"
